//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.SubjectInScheduleViewModel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SubjectTypes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SubjectTypes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Views.SubjectInScheduleViewModel.SubjectTypes", typeof(SubjectTypes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excercise.
        /// </summary>
        public static string Exercise {
            get {
                return ResourceManager.GetString("Exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excercise and practice.
        /// </summary>
        public static string ExerciseAndPractice {
            get {
                return ResourceManager.GetString("ExerciseAndPractice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecture.
        /// </summary>
        public static string Lecture {
            get {
                return ResourceManager.GetString("Lecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecture and excercise.
        /// </summary>
        public static string LectureAndExercise {
            get {
                return ResourceManager.GetString("LectureAndExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecture and practice.
        /// </summary>
        public static string LectureAndPractice {
            get {
                return ResourceManager.GetString("LectureAndPractice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice.
        /// </summary>
        public static string Practice {
            get {
                return ResourceManager.GetString("Practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice and excercise.
        /// </summary>
        public static string PracticeAndExercise {
            get {
                return ResourceManager.GetString("PracticeAndExercise", resourceCulture);
            }
        }
    }
}
