//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Domain.ScheduleAndEventView {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ScheduleAndEvent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScheduleAndEvent() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Domain.ScheduleAndEventView.ScheduleAndEvent", typeof(ScheduleAndEvent).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add event.
        /// </summary>
        public static string AddEvent {
            get {
                return ResourceManager.GetString("AddEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add lecture.
        /// </summary>
        public static string AddLecture {
            get {
                return ResourceManager.GetString("AddLecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this event?.
        /// </summary>
        public static string DeleteEventMessage {
            get {
                return ResourceManager.GetString("DeleteEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this subject from schedule?.
        /// </summary>
        public static string DeleteSubjectMessage {
            get {
                return ResourceManager.GetString("DeleteSubjectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event date and time.
        /// </summary>
        public static string EventDateTime {
            get {
                return ResourceManager.GetString("EventDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event name.
        /// </summary>
        public static string EventName {
            get {
                return ResourceManager.GetString("EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        public static string EventPlace {
            get {
                return ResourceManager.GetString("EventPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show from-to.
        /// </summary>
        public static string EventShowFromTo {
            get {
                return ResourceManager.GetString("EventShowFromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecture name .
        /// </summary>
        public static string LectureNameWithCode {
            get {
                return ResourceManager.GetString("LectureNameWithCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecturers.
        /// </summary>
        public static string Lecturers {
            get {
                return ResourceManager.GetString("Lecturers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lectures.
        /// </summary>
        public static string Lectures {
            get {
                return ResourceManager.GetString("Lectures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        public static string LectureType {
            get {
                return ResourceManager.GetString("LectureType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh schedule.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All saved changes will be overwritten! Are you sure you want to continue?.
        /// </summary>
        public static string RefreshQuestion {
            get {
                return ResourceManager.GetString("RefreshQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        public static string Rooms {
            get {
                return ResourceManager.GetString("Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule is being updated. It will take about 20 seconds..
        /// </summary>
        public static string ScheduleUpdateMessage {
            get {
                return ResourceManager.GetString("ScheduleUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string StartToEndString {
            get {
                return ResourceManager.GetString("StartToEndString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
    }
}
