//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Domain.ScreenView {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Screen {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Screen() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Domain.ScreenView.Screen", typeof(Screen).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add background.
        /// </summary>
        public static string AddBackground {
            get {
                return ResourceManager.GetString("AddBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background picture.
        /// </summary>
        public static string BackgroundPic {
            get {
                return ResourceManager.GetString("BackgroundPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to screen.
        /// </summary>
        public static string BackToScreen {
            get {
                return ResourceManager.GetString("BackToScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new screen.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default is used.
        /// </summary>
        public static string DefaultUsed {
            get {
                return ResourceManager.GetString("DefaultUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete promotion.
        /// </summary>
        public static string DeletePromotion {
            get {
                return ResourceManager.GetString("DeletePromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this promotion?.
        /// </summary>
        public static string DeletePromotionText {
            get {
                return ResourceManager.GetString("DeletePromotionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivate.
        /// </summary>
        public static string Inactivate {
            get {
                return ResourceManager.GetString("Inactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading new schedule....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No promotions found! You do not have rights to add the promotion!.
        /// </summary>
        public static string NoPromoFound {
            get {
                return ResourceManager.GetString("NoPromoFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not active.
        /// </summary>
        public static string NotActive {
            get {
                return ResourceManager.GetString("NotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        public static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no timeplan with such prefix. Whether it is study-free day or the prefix is incorrect!.
        /// </summary>
        public static string PrefixError {
            get {
                return ResourceManager.GetString("PrefixError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotions.
        /// </summary>
        public static string Promotions {
            get {
                return ResourceManager.GetString("Promotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule status.
        /// </summary>
        public static string ScheduleStatus {
            get {
                return ResourceManager.GetString("ScheduleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule search prefix.
        /// </summary>
        public static string SearchPrefix {
            get {
                return ResourceManager.GetString("SearchPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See promotion.
        /// </summary>
        public static string SeePromotion {
            get {
                return ResourceManager.GetString("SeePromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show always.
        /// </summary>
        public static string ShowAlways {
            get {
                return ResourceManager.GetString("ShowAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shown.
        /// </summary>
        public static string Shown {
            get {
                return ResourceManager.GetString("Shown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show schedule.
        /// </summary>
        public static string ShowSchedule {
            get {
                return ResourceManager.GetString("ShowSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use default.
        /// </summary>
        public static string UseDefault {
            get {
                return ResourceManager.GetString("UseDefault", resourceCulture);
            }
        }
    }
}
